### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by 0v3rt1r3d** [bitgate/maya-ogre3d-exporter#2]
Hi! As I figured out of the readme, the exporter could be built for windows platform only. Is there a way to build it for mac os?

**Comment by aristotaloss** [comment]
Hi! I have never tried to build it on a Mac, and it may just work fine, but I recon you need to do some configuring and searching - if I have some time I can take a look :)

**Comment by 0v3rt1r3d** [comment]
I tried to build to it, but faced with the compiler incompatibility. As I understood from https://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__files_Setting_up_your_build_environment_Mac_OS_X_environment_htm, too old mac os and compiler required, which is not possible for me to install.
